### ISSUE TITLE
Introduce optional argument in cat-at

### ISSUE THREAD

**Issue by EeshaArif** [Diaga/Distributed-Finder#46]
`cat-at <index> <filename>` needs an extra argument `size` but has to be optional since `cat-at -w <index> <filename>` takes two arguments 

Linked to #45

**Comment by Diaga** [comment]
Each argument accepts a parameter `required`. It can be set to `False` to make the argument optional.

**Comment by EeshaArif** [comment]
Tried that already, could not make it work

**Comment by Diaga** [comment]
Okk, I will look at it #45 gets merged!
