### ISSUE TITLE
Still no open, close function

### ISSUE THREAD

**Issue by EeshaArif** [Diaga/Distributed-Finder#48]
The open function was supposed to return the file object and that object was supposed to call functions.
The design did not support that

**Comment by Diaga** [comment]
Forgot to get back to you guys.
![image](https://user-images.githubusercontent.com/38937684/100723634-d3446600-33e3-11eb-9e5e-8beb889ef4f7.png)

We do not need open, close functions implemented and file objects manipulated by user. They just need to be implemented internally, just like we are doing ⭐

**Comment by EeshaArif** [comment]
:) kill yourself for me please...
